#pragma once

// Engine function addresses for Morrowind.exe (the Morrowind game binary).
// Consumers select the appropriate target via a thin per-project NIConfig.h shim.

// NI::Matrix33
#define SE_NI_MATRIX33_FNADDR_ADDMATRIX 0x6E7F60
#define SE_NI_MATRIX33_FNADDR_FROMEULERXYZ 0x6E8D60
#define SE_NI_MATRIX33_FNADDR_INVERSE 0x6E83E0
#define SE_NI_MATRIX33_FNADDR_INVERSERAW 0x6E82F0
#define SE_NI_MATRIX33_FNADDR_MULTIPLYMATRIX 0x6E80A0
#define SE_NI_MATRIX33_FNADDR_MULTIPLYSCALAR 0x6E81B0
#define SE_NI_MATRIX33_FNADDR_MULTIPLYVECTOR 0x6E8230
#define SE_NI_MATRIX33_FNADDR_REORTHOGONALIZE 0x6E84A0
#define SE_NI_MATRIX33_FNADDR_SUBTRACTMATRIX 0x6E8000
#define SE_NI_MATRIX33_FNADDR_TESTEQUAL 0x6E7ED0
#define SE_NI_MATRIX33_FNADDR_TOEULERXYZ 0x6E8C50
#define SE_NI_MATRIX33_FNADDR_TOIDENTITY 0x6E7CF0
#define SE_NI_MATRIX33_FNADDR_TOROTATIONX 0x6E7D20
#define SE_NI_MATRIX33_FNADDR_TOROTATIONXYZ 0x6E7DE0
#define SE_NI_MATRIX33_FNADDR_TOROTATIONY 0x6E7D60
#define SE_NI_MATRIX33_FNADDR_TOROTATIONZ 0x6E7DA0
#define SE_NI_MATRIX33_FNADDR_TRANSPOSE 0x6E8420

// NI::Quaternion
#define SE_NI_QUATERNION_FNADDR_FROMANGLEAXIS 0x6FBDF0
#define SE_NI_QUATERNION_FNADDR_FROMROTATION 0x6FBEF0
#define SE_NI_QUATERNION_FNADDR_INVERT 0x0
#define SE_NI_QUATERNION_FNADDR_MULTIPLYQUATERNION 0x6FB6A0
#define SE_NI_QUATERNION_FNADDR_SLERP 0x6FB7F0
#define SE_NI_QUATERNION_FNADDR_TOANGLEAXIS 0x6FBE20

// NI::Object
#define SE_NI_OBJECT_FNADDR_CREATECLONE 0x0
#define SE_NI_OBJECT_FNADDR_CTOR 0x6E98A0
#define SE_NI_OBJECT_FNADDR_DTOR 0x6E98F0
#define SE_NI_OBJECT_FNADDR_REGISTERSTREAMABLES 0x6E9BF0

// NI::ObjectNET
#define SE_NI_OBJECTNET_FNADDR_ADDEXTRADATA 0x6EA1C0
#define SE_NI_OBJECTNET_FNADDR_PREPENDCONTROLLER 0x6EA3E0
#define SE_NI_OBJECTNET_FNADDR_REMOVEALLCONTROLLERS 0x6EA5A0
#define SE_NI_OBJECTNET_FNADDR_REMOVEALLEXTRADATA 0x6EA3B0
#define SE_NI_OBJECTNET_FNADDR_REMOVECONTROLLER 0x6EA450
#define SE_NI_OBJECTNET_FNADDR_REMOVEEXTRADATA 0x6EA260
#define SE_NI_OBJECTNET_FNADDR_SETFLAG 0x0
#define SE_NI_OBJECTNET_FNADDR_SETNAME 0x6EA1A0

// NI::AVObject
#define SE_NI_AVOBJECT_FNADDR_ATTACHPROPERTY 0x0
#define SE_NI_AVObject_FNADDR_DETACHPROPERTYBYTYPE 0x5DADD0
#define SE_NI_AVOBJECT_FNADDR_SETLOCALROTATIONMATRIX 0x0
#define SE_NI_AVOBJECT_FNADDR_UPDATE 0x0
#define SE_NI_AVOBJECT_FNADDR_UPDATEEFFECTS 0x0
#define SE_NI_AVOBJECT_FNADDR_UPDATEPROPERTIES 0x0

// NI::Node
#define SE_NI_NODE_FNADDR_ATTACHEFFECT 0x6C91E0
#define SE_NI_NODE_FNADDR_CTOR 0x6C81E0
#define SE_NI_NODE_FNADDR_DETACHALLEFFECTS 0x6C92C0
#define SE_NI_NODE_FNADDR_DETACHEFFECT 0x6C9220

// NI::DynamicEffect
#define SE_NI_DYNAMICEFFECT_FNADDR_ATTACHAFFECTEDNODE 0x6F3790
#define SE_NI_DYNAMICEFFECT_FNADDR_CTOR 0x6F34E0
#define SE_NI_DYNAMICEFFECT_FNADDR_DETACHAFFECTEDNODE 0x6F37D0
#define SE_NI_FNADDR_CLEARDYNAMICEFFECTNODES 0x0

// NI::Property
#define SE_NI_PROPERTY_FNADDR_CTOR 0x405990
#define SE_NI_PROPERTY_FNADDR_DTOR 0x405B40
#define SE_NI_PROPERTY_FNADDR_SETFLAGBITFIELD 0x408A10

// NI::AlphaProperty
#define SE_NI_ALPHAPROPERTY_VTBL 0x0

// NI::TexturingProperty::Map
#define SE_NI_TEXTURINGPROPERTY_MAP_FNADDR_CTOR 0x42DCD0
#define SE_NI_TEXTURINGPROPERTY_MAP_FNADDR_CTORWITHPARAMS 0x4CEEC0

// NI::TexturingProperty::BumpMap
#define SE_NI_TEXTURINGPROPERTY_BUMPMAP_VTBL 0x0

// NI::TexturingProperty
#define SE_NI_TEXTURINGPROPERTY_FNADDR_CTOR 0x0
#define SE_NI_TEXTURINGPROPERTY_FNADDR_DTOR 0x0

// NI::VertexColorProperty
#define SE_NI_VERTEXCOLORPROPERTY_VTBL 0x0

// NI::ZBufferProperty
#define SE_NI_ZBUFFERPROPERTY_VTBL 0x0

// NI::SkinInstance
#define SE_NI_SKININSTANCE_FNADDR_DEFORM 0x6FA000

// NI::TriShape
#define SE_NI_TRISHAPE_FNADDR_CTOR 0x0

// NI::TriShapeData
#define SE_NI_TRISHAPEDATA_FNADDR_CREATE 0x0

// NI::Lines
#define SE_NI_LINES_FNADDR_CTOR 0x0

// NI::GeometryData
#define SE_NI_GEOMETRYDATA_FNADDR_LOADBINARY 0x6EF5E0

// NI::StringExtraData
#define SE_NI_STRINGEXTRADATA_FNADDR_CTOR 0x6E0EB0
#define SE_NI_STRINGEXTRADATA_FNADDR_DTOR 0x6E1530

// NI::Texture
#define SE_NI_TEXTURE_FNADDR_DEFAULT_PREFS 0x7DE3B4

// NI::TimeController
#define SE_NI_TIMECONTROLLER_FNADDR_COPY 0x6FC8E0

// NI::Camera
#define SE_NI_CAMERA_FNADDR_CLEAR 0x6CC780
#define SE_NI_CAMERA_FNADDR_CLICK 0x6CC7B0
#define SE_NI_CAMERA_FNADDR_CTOR 0x6CC200
#define SE_NI_CAMERA_FNADDR_DTOR 0x6CC510
#define SE_NI_CAMERA_FNADDR_LOOKATWORLDPOINT 0x6CD5D0
#define SE_NI_CAMERA_FNADDR_SWAPBUFFERS 0x6CC930
#define SE_NI_CAMERA_FNADDR_WINDOWPOINTTORAY 0x6CDA70
#define SE_NI_CAMERA_FNADDR_WORLDPOINTTOSCREENPOINT 0x6CD450

// NI::Pick
#define SE_NI_PICK_FNADDR_CLEARRESULTS 0x6F2F80
#define SE_NI_PICK_FNADDR_CTOR 0x6F2DF0
#define SE_NI_PICK_FNADDR_DTOR 0x6F2EA0
#define SE_NI_PICK_FNADDR_PICKOBJECTS 0x6F3050

// NI::Stream
#define SE_NI_STREAM_FNADDR_CTOR 0x6C2B60
#define SE_NI_STREAM_FNADDR_DTOR 0x6C2DD0
#define SE_NI_STREAM_FNADDR_GETCOPIEDOBJECT 0x7DE768
#define SE_NI_STREAM_FNADDR_GETLINKID 0x6C3730
#define SE_NI_STREAM_FNADDR_GETLINKOBJECT 0x6C3640
#define SE_NI_STREAM_FNADDR_INSERTOBJECT 0x6C2FD0
#define SE_NI_STREAM_FNADDR_LOAD 0x6C41D0
#define SE_NI_STREAM_FNADDR_READSTRING 0x6C4C20
#define SE_NI_STREAM_FNADDR_REGISTERLOADER 0x6C4460
#define SE_NI_STREAM_FNADDR_SAVE 0x6C4710
#define SE_NI_STREAM_FNADDR_WRITESTRING 0x6C4C80

// NI::Stream::LoadingObject
#define SE_NI_STREAM_LOADINGOBJECT_VTBL 0x74F36C

// NI::Bound
#define SE_NI_BOUND_FNADDR_COMPUTEFROMDATA 0x6ED170
