#pragma once

// Engine function addresses for Morrowind.exe (the Morrowind game binary).
// Consumers select the appropriate target via a thin per-project NIConfig.h shim.

// NI::Matrix33
#define SE_NI_MATRIX33_FNADDR_ADDMATRIX 0x6E7F60
#define SE_NI_MATRIX33_FNADDR_FROMEULERXYZ 0x6E8D60
#define SE_NI_MATRIX33_FNADDR_INVERSE 0x6E83E0
#define SE_NI_MATRIX33_FNADDR_INVERSERAW 0x6E82F0
#define SE_NI_MATRIX33_FNADDR_MULTIPLYMATRIX 0x6E80A0
#define SE_NI_MATRIX33_FNADDR_MULTIPLYSCALAR 0x6E81B0
#define SE_NI_MATRIX33_FNADDR_MULTIPLYVECTOR 0x6E8230
#define SE_NI_MATRIX33_FNADDR_REORTHOGONALIZE 0x6E84A0
#define SE_NI_MATRIX33_FNADDR_SUBTRACTMATRIX 0x6E8000
#define SE_NI_MATRIX33_FNADDR_TESTEQUAL 0x6E7ED0
#define SE_NI_MATRIX33_FNADDR_TOEULERXYZ 0x6E8C50
#define SE_NI_MATRIX33_FNADDR_TOIDENTITY 0x6E7CF0
#define SE_NI_MATRIX33_FNADDR_TOROTATIONX 0x6E7D20
#define SE_NI_MATRIX33_FNADDR_TOROTATIONXYZ 0x6E7DE0
#define SE_NI_MATRIX33_FNADDR_TOROTATIONY 0x6E7D60
#define SE_NI_MATRIX33_FNADDR_TOROTATIONZ 0x6E7DA0
#define SE_NI_MATRIX33_FNADDR_TRANSPOSE 0x6E8420

// NI::Quaternion
#define SE_NI_QUATERNION_FNADDR_FROMANGLEAXIS 0x6FBDF0
#define SE_NI_QUATERNION_FNADDR_FROMROTATION 0x6FBFC0
#define SE_NI_QUATERNION_FNADDR_INVERT 0x6FB730
#define SE_NI_QUATERNION_FNADDR_EXP 0x6FD9D0
#define SE_NI_QUATERNION_FNADDR_LOG 0x6FB760
#define SE_NI_QUATERNION_FNADDR_MULTIPLYQUATERNION 0x6FB6A0
#define SE_NI_QUATERNION_FNADDR_SLERP 0x6FB7F0
#define SE_NI_QUATERNION_FNADDR_TOANGLEAXIS 0x6FBE20

// NI::Object
#define SE_NI_OBJECT_FNADDR_CREATECLONE 0x6E9910
#define SE_NI_OBJECT_FNADDR_CTOR 0x6E98A0
#define SE_NI_OBJECT_FNADDR_DTOR 0x6E98F0
#define SE_NI_OBJECT_FNADDR_RELEASE 0x404630
#define SE_NI_OBJECT_FNADDR_REGISTERSTREAMABLES 0x6E9BF0

// NI::ObjectNET
#define SE_NI_OBJECTNET_FNADDR_ADDEXTRADATA 0x6EA1C0
#define SE_NI_OBJECTNET_FNADDR_PREPENDCONTROLLER 0x6EA3E0
#define SE_NI_OBJECTNET_FNADDR_REMOVEALLCONTROLLERS 0x6EA5A0
#define SE_NI_OBJECTNET_FNADDR_REMOVEALLEXTRADATA 0x6EA3B0
#define SE_NI_OBJECTNET_FNADDR_REMOVECONTROLLER 0x6EA450
#define SE_NI_OBJECTNET_FNADDR_REMOVEEXTRADATA 0x6EA260
#define SE_NI_OBJECTNET_FNADDR_SETFLAG 0x0
#define SE_NI_OBJECTNET_FNADDR_SETNAME 0x6EA1A0

// NI::AVObject
#define SE_NI_AVOBJECT_FNADDR_ATTACHPROPERTY 0x405840
#define SE_NI_AVObject_FNADDR_DETACHPROPERTYBYTYPE 0x6EAE20
#define SE_NI_AVOBJECT_FNADDR_SETFLAG 0x405960
#define SE_NI_AVOBJECT_FNADDR_INTERSECTBOUNDS 0x6EB930
#define SE_NI_AVOBJECT_FNADDR_SETMODELSPACEABV 0x6EB590
#define SE_NI_AVOBJECT_FNADDR_SETLOCALROTATIONMATRIX 0x50E020
#define SE_NI_AVOBJECT_FNADDR_UPDATE 0x6EB000
#define SE_NI_AVOBJECT_FNADDR_UPDATEEFFECTS 0x6EB380
#define SE_NI_AVOBJECT_FNADDR_UPDATEPROPERTIES 0x6EB0E0

// NI::Matrix33 identity matrix global
#define SE_NI_MATRIX33_GLOBADDR_IDENTITY 0x7DE664

// NI::Node
#define SE_NI_NODE_FNADDR_ATTACHEFFECT 0x6C91E0
#define SE_NI_NODE_FNADDR_CTOR 0x6C81E0
#define SE_NI_NODE_FNADDR_DETACHALLEFFECTS 0x6C92C0
#define SE_NI_NODE_FNADDR_DETACHEFFECT 0x6C9220
#define SE_NI_NODE_FNADDR_FINDINTERSECTIONS 0x6C9F20
#define SE_NI_NODE_FNADDR_LINKOBJECT 0x6CA7F0

// NI::CollisionSwitch vTable address
#define SE_NI_COLLISIONSWITCH_VTBL 0x74F418

// NI::Particles
#define SE_NI_PARTICLES_VTBL 0x74FCE8
#define SE_NI_PARTICLESDATA_FNADDR_CTOR 0x6D1ED0

// NI::AutoNormalParticles
#define SE_NI_AUTONORMALPARTICLES_VTBL 0x74FDE8
#define SE_NI_AUTONORMALPARTICLESDATA_FNADDR_CTOR 0x6D3020

// NI::PointLight vTable address (DynamicEffect_vTable layout)
#define SE_NI_POINTLIGHT_VTBL 0x749D40

// NI::KeyframeData
#define SE_NI_KEYFRAMEDATA_FNADDR_REPLACESCALEDATA 0x70D420

// NI::SortAdjustNode vTable address
#define SE_NI_SORTADJUSTNODE_VTBL 0x750580

// NI light-radius test (cdecl free function; used by Node::shouldBeAffectedByLight)
#define SE_NI_FNADDR_LIGHTRADIUSTEST 0x4D19C0

// NI::DynamicEffect
#define SE_NI_DYNAMICEFFECT_FNADDR_ATTACHAFFECTEDNODE 0x6F3790
#define SE_NI_DYNAMICEFFECT_FNADDR_CTOR 0x6F34E0
#define SE_NI_DYNAMICEFFECT_FNADDR_DETACHAFFECTEDNODE 0x6F37D0
#define SE_NI_FNADDR_CLEARDYNAMICEFFECTNODES 0x0

// NI::Property
#define SE_NI_PROPERTY_FNADDR_CTOR 0x405990
#define SE_NI_PROPERTY_FNADDR_DTOR 0x405B40
#define SE_NI_PROPERTY_FNADDR_SETFLAG 0x405960
#define SE_NI_PROPERTY_FNADDR_SETFLAGBITFIELD 0x408A10

// NI::AlphaProperty
#define SE_NI_ALPHAPROPERTY_VTBL 0x7465A8

// NI::StencilProperty
#define SE_NI_STENCILPROPERTY_VTBL 0x746A5C

// NI::TexturingProperty::Map
#define SE_NI_TEXTURINGPROPERTY_MAP_FNADDR_CTOR 0x42DCD0
#define SE_NI_TEXTURINGPROPERTY_MAP_FNADDR_CTORWITHPARAMS 0x4CEEC0

// NI::TexturingProperty::BumpMap
#define SE_NI_TEXTURINGPROPERTY_BUMPMAP_VTBL 0x7507B0

// NI::TexturingProperty
#define SE_NI_TEXTURINGPROPERTY_FNADDR_CTOR 0x0
#define SE_NI_TEXTURINGPROPERTY_FNADDR_DTOR 0x0

// NI::VertexColorProperty
#define SE_NI_VERTEXCOLORPROPERTY_VTBL 0x7464F8

// NI::ZBufferProperty
#define SE_NI_ZBUFFERPROPERTY_VTBL 0x74652C

// NI::Light
#define SE_NI_LIGHT_FNADDR_CTOR 0x6F9940

// NI::SkinInstance
#define SE_NI_SKININSTANCE_FNADDR_DEFORM 0x6FA000

// NI::TriShape
#define SE_NI_TRISHAPE_FNADDR_CTOR 0x0

// NI::TriShapeData
#define SE_NI_TRISHAPEDATA_FNADDR_CREATE 0x6E4690

// NI::Lines
#define SE_NI_LINES_FNADDR_CTOR 0x0

// NI::GeometryData
#define SE_NI_GEOMETRYDATA_FNADDR_LOADBINARY 0x6EF5E0

// NI::PixelData
#define SE_NI_PIXELDATA_FNADDR_CTOR_ARGS 0x6D4FC0
#define SE_NI_PIXELFORMAT_GLOBADDR_RGBA32 0x7DE8B8

// NI::StringExtraData
#define SE_NI_STRINGEXTRADATA_FNADDR_CTOR 0x6E0EB0
#define SE_NI_STRINGEXTRADATA_FNADDR_DTOR 0x6E1530

// NI::Texture
#define SE_NI_TEXTURE_FNADDR_DEFAULT_PREFS 0x7DE3B4

// NI::TimeController
#define SE_NI_TIMECONTROLLER_FNADDR_COPY 0x6FC8E0

// NI::Camera
#define SE_NI_CAMERA_FNADDR_CLEAR 0x6CC780
#define SE_NI_CAMERA_FNADDR_CLICK 0x6CC7B0
#define SE_NI_CAMERA_FNADDR_CTOR 0x6CC200
#define SE_NI_CAMERA_FNADDR_DTOR 0x6CC510
#define SE_NI_CAMERA_FNADDR_LOOKATWORLDPOINT 0x6CD5D0
#define SE_NI_CAMERA_FNADDR_SWAPBUFFERS 0x6CC930
#define SE_NI_CAMERA_FNADDR_WINDOWPOINTTORAY 0x6CDA70
#define SE_NI_CAMERA_FNADDR_WORLDPOINTTOSCREENPOINT 0x6CD450

// NI::Pick
#define SE_NI_PICK_FNADDR_CLEARRESULTS 0x6F2F80
#define SE_NI_PICK_FNADDR_CTOR 0x6F2DF0
#define SE_NI_PICK_FNADDR_DTOR 0x6F2EA0
#define SE_NI_PICK_FNADDR_PICKOBJECTS 0x6F3050

// NI::Stream
#define SE_NI_STREAM_FNADDR_CTOR 0x6C2B60
#define SE_NI_STREAM_FNADDR_DTOR 0x6C2DD0
#define SE_NI_STREAM_FNADDR_GETCOPIEDOBJECT 0x7DE768
#define SE_NI_STREAM_FNADDR_GETLINKID 0x6C3730
#define SE_NI_STREAM_FNADDR_GETLINKOBJECT 0x6C3640
#define SE_NI_STREAM_FNADDR_INSERTOBJECT 0x6C2FD0
#define SE_NI_STREAM_FNADDR_LOAD 0x6C41D0
#define SE_NI_STREAM_FNADDR_READSTRING 0x6C4C20
#define SE_NI_STREAM_FNADDR_REGISTERLOADER 0x6C4460
#define SE_NI_STREAM_FNADDR_SAVE 0x6C4710
#define SE_NI_STREAM_FNADDR_WRITESTRING 0x6C4C80

// NI::Stream::LoadingObject
#define SE_NI_STREAM_LOADINGOBJECT_VTBL 0x74F36C

// NI::Bound
#define SE_NI_BOUND_FNADDR_COMPUTEFROMDATA 0x6ED170

// NI::BoxBoundingVolume
#define SE_NI_BOXBOUNDINGVOLUME_FNADDR_CREATE 0x694C10

// NI::TriBasedGeometry
#define SE_NI_TRIBASEDGEOMETRY_FNADDR_CTORFROMDATA 0x6EFEA0
#define SE_NI_TRIBASEDGEOMETRY_FNADDR_FINDINTERSECTIONS 0x6F0350
#define SE_NI_FNADDR_FINDINTERSECTRAYWITHTRIANGLE 0x6EFF90

// NI::Geometry (base of TriBasedGeometry)
#define SE_NI_GEOMETRY_FNADDR_LINKOBJECT 0x6F47D0

// NI::TriShape vTable address (Object_vTable layout)
#define SE_NI_TRISHAPE_VTBL 0x7508B0
