--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- This event is called when an animation is triggered using the LuaEvent key.
--- @class animationTriggerEventData
--- @field claim boolean If set to `true`, any lower-priority event callbacks will be skipped. Returning `false` will set this to `true`.
--- @field name string *Read-only*. The name of the animation triggered.
--- @field param string|nil *Read-only*. The parameter string associated with the animation.
--- @field reference tes3reference *Read-only*. The reference that the animation has been triggered on.
