--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- This event is triggered when keyframes have been parsed, but before they have been loaded into animation groups. It can be used to add, remove, or convert file keyframe data.
--- @class keyframesParsedEventData
--- @field claim boolean If set to `true`, any lower-priority event callbacks will be skipped. Returning `false` will set this to `true`.
--- @field path string The path to the keyframes file, relative to Data Files\Meshes.
--- @field textKeys {time: number, key: string, value: string}[] An array of the loaded text key definition. Entries can be modified or inserted as tables with the keys `time`, `key`, and `value`.
