--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- This event triggers when a magic source removes the last active instance for one of its effects.
--- 
--- For a magic source with multiple effects, this event triggers once for each effect that ends. If the same source effect is active on multiple references, `magicEffectDeactivated` can trigger as each reference stops being affected, but `magicEffectEnded` only triggers when the final stored instance of that source effect is retired.
---
--- [Examples available in online documentation](https://mwse.github.io/MWSE/events/magicEffectEnded).
--- @class magicEffectEndedEventData
--- @field claim boolean If set to `true`, any lower-priority event callbacks will be skipped. Returning `false` will set this to `true`.
--- @field caster tes3reference *Read-only*. The caster of the magic source. Can be `nil`.
--- @field effect tes3effect *Read-only*. The specific effect that triggered the event. This is equal to `e.source.effects[e.effectIndex]`. Can be `nil`.
--- @field effectIndex integer *Read-only*. The index of the effect in the magic source's effects list.
--- @field effectInstance tes3magicEffectInstance *Read-only*. The unique instance of the magic effect that caused the source effect to end.
--- @field source tes3alchemy|tes3enchantment|tes3spell *Read-only*. The magic source that contains the effect.
--- @field sourceInstance tes3magicSourceInstance *Read-only*. The unique instance of the magic source that contains the effect.
--- @field state tes3.spellState *Read-only*. The state of the magic effect instance when the event fired.
--- @field target tes3reference *Read-only*. The target of the magic effect instance that caused the source effect to end.
