--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- Fires at the end of each frame, right before rendering. All game logic and scene updates are complete, so this is the final opportunity to modify the scene before it's drawn.
--- 	
--- @class renderEventData
--- @field claim boolean If set to `true`, any lower-priority event callbacks will be skipped. Returning `false` will set this to `true`.
