--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- This event is fired after a Morrowind script finishes executing.
--- @class scriptExecutedEventData
--- @field claim boolean If set to `true`, any lower-priority event callbacks will be skipped. Returning `false` will set this to `true`.
--- @field info tes3dialogueInfo|nil *Read-only*. The dialogue info associated with this script execution, if any.
--- @field reference tes3reference|nil *Read-only*. The primary reference passed to the script, if any.
--- @field reference2 tes3reference|nil *Read-only*. The secondary reference passed to the script, if any.
--- @field script tes3script *Read-only*. The script that finished executing.
--- @field variables table *Read-only*. A snapshot of the script variables that were used during execution.
