--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- The spellProjectileHitWater event fires when a spell projectile collides with water.
--- @class spellProjectileHitWaterEventData
--- @field claim boolean If set to `true`, any lower-priority event callbacks will be skipped. Returning `false` will set this to `true`.
--- @field collisionPoint tes3vector3 *Read-only*. The collision point of the spell projectile.
--- @field firingReference tes3reference *Read-only*. Reference to the actor that fired the projectile.
--- @field mobile tes3mobileSpellProjectile *Read-only*. The spell projectile that is expiring.
--- @field position tes3vector3 *Read-only*. The position of the spell projectile at collision.
--- @field target tes3reference *Read-only*. Reference hit by the spell projectile, if available.
--- @field velocity tes3vector3 *Read-only*. The velocity of the spell projectile at collision.
