--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- Occurs when a region picks a new weather during weather cycling or weather-related script operations. It exposes the region's base weather chances as a mutable dictionary keyed by raw weather index. Lua may overwrite vanilla weights, remove them by setting them to `0`, or add positive weights for custom weather IDs. The resulting weights do not need to total 100.
---
--- [Examples available in online documentation](https://mwse.github.io/MWSE/events/weatherSelect).
--- @class weatherSelectEventData
--- @field claim boolean If set to `true`, any lower-priority event callbacks will be skipped. Returning `false` will set this to `true`.
--- @field chances table A mutable dictionary of weather weights keyed by weather index. Only entries with positive numeric weights and a loaded weather object are considered during selection.
--- @field region tes3region *Read-only*. The region selecting a new weather.
