-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- @diagnostic disable:undefined-doc-name

--- An object used to store MWSE's configuration.
--- @class mwseConfig
--- @field EnableLegacyLuaMods boolean? *Default*: `true`. If enabled, early alpha lua mods will be supported. Legacy lua mods can be found in: `Data Files\MWSE\lua` folder.
--- @field EnableLogColors boolean? *Default*: `false`. If enabled, log colors will be enabled in the console. However, this will make the `mwse.log` file more difficult to read in a text editor.
--- @field KeepAllNetImmerseObjectsAlive boolean? *Default*: `false`. WARNING: Only used for debugging purposes. Enabling this without knowing what you're doing WILL lead to memory leaks. When enabled, NetImmerse objects will use the same lua object caching system that TES3 objects use, allowing them to be string-compared or used as table keys.
--- @field LetterboxMovies boolean? *Default*: `false`. Morrowind stretches movies to fill the whole window by default. This option will instead render movies with black bars to either side, centering the movie in the window.
--- @field LogWarningsWithLuaStack boolean? *Default*: `true`. When enabled, any warnings raised during normal gameplay that would write to `warnings.txt` will also write to `mwse.log`. In addition, a stack trace is provided to give context to what mod may be responsible for the warning. This can lead to superfluous log entries when using certain mods, like Better Bodies.
--- @field PatchNiFlipController boolean? *Default*: `true`. Morrowind incorrectly handles the affected map when cloning NiFlipController objects, preventing mods from using the controller for anything but the base map. MWSE fixes this issue. However, some mods contain bugged assets that have the incorrect affected map assigned, relying on the bug to reassign the controller back to the base map. Disabling this fix will provide support for these mods, but will also prevent newer mods from taking advantage of the fixed controller. It is recommended that you leave this enabled unless you know you need the compatibility.
--- @field RunInBackground boolean? *Default*: `false`. By default Morrowind skips most game logic when not in focus. When using windowed mode (including borderless fullscreen), this feature allows Morrowind to continue running. Enabling this can also help to increase stability, due to how Morrowind handles some audio threads.
mwseConfig = {}

--- Returns a table with the default MWSE settings.
--- @return table<string, boolean> defaultConfig No description yet available.
function mwseConfig.getDefaults() end

