-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- A slider for dealing with percentages. Values will be stored in the range 0.0-1.0 and displayed in the range 0-100.
--- @class mwseMCMPercentageSlider : mwseMCMSlider, mwseMCMSetting, mwseMCMComponent
--- @field decimalPlaces integer The number of (displayed) decimal places of precision. Must be a nonnegative integer. e.g., specifying `1` will allow "5.4" to be displayed. Default is `0`.
--- @field max number Maximum (displayed) value of slider. Default is `100`. (The maximum stored value will be `1.0`.)
--- @field min number Minimum (displayed) value of slider. Default is `100`. (The minimum stored value will be `1.0`.)
mwseMCMPercentageSlider = {}

--- This method creates the UI elements specific to Slider.
--- @param parentBlock tes3uiElement No description yet available.
function mwseMCMPercentageSlider:createContentsContainer(parentBlock) end

--- Scales given `value` from the variable range to the range used by the underlying `tes3uiSlider` widget.
--- @param value number No description yet available.
--- @return number scaledValue No description yet available.
function mwseMCMPercentageSlider:scaleToSliderRange(value) end

--- Scales given `value` from the underlying `tes3uiSlider` widget's range to the range used by the variable.
--- @param value number No description yet available.
--- @return number scaledValue No description yet available.
function mwseMCMPercentageSlider:scaleToVariableRange(value) end

--- Updates the label text of the slider to show the current value of the slider.
function mwseMCMPercentageSlider:updateValueLabel() end

