--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- A rendering property that controls the methods used to filter texture pixels, and blend texture colors and vertex colors.
--- @class niTexturingProperty : niProperty, niObjectNET, niObject
--- @field applyMode ni.texturingPropertyApplyMode The texture apply mode. The texture apply mode controls how the vertex colors are blended with the texture color. Maps to values in [`ni.texturingPropertyApplyMode`](https://mwse.github.io/MWSE/references/ni/texturing-property-apply-modes/) table.
--- @field baseMap niTexturingPropertyMap|nil Gets or set the base map. Can be set to nil to delete it. Note that doing so will free the memory of the map, causing all existing handles to it to become invalid.
--- @field bumpMap niTexturingPropertyMap|nil Gets or set the bump map. Can be set to nil to delete it. Note that doing so will free the memory of the map, causing all existing handles to it to become invalid.
--- @field canAddDecal boolean *Read-only*. If true, the texturing property supports additional decal maps.
--- @field darkMap niTexturingPropertyMap|nil Gets or set the dark map. Can be set to nil to delete it. Note that doing so will free the memory of the map, causing all existing handles to it to become invalid.
--- @field decalCount integer *Read-only*. The number of decals currently on the texturing property.
--- @field detailMap niTexturingPropertyMap|nil Gets or set the detail map. Can be set to nil to delete it. Note that doing so will free the memory of the map, causing all existing handles to it to become invalid.
--- @field glossMap niTexturingPropertyMap|nil Gets or set the gloss map. Can be set to nil to delete it. Note that doing so will free the memory of the map, causing all existing handles to it to become invalid.
--- @field glowMap niTexturingPropertyMap|nil Gets or set the glow map. Can be set to nil to delete it. Note that doing so will free the memory of the map, causing all existing handles to it to become invalid.
--- @field maps niTexturingPropertyMap[] *Read-only*. The maps of texture property. Accessible as an array.
niTexturingProperty = {}

--- Attempts to create a new decal map. If successful, it returns both the new map and the index it was created in.
--- @param texture? niRenderedTexture|niSourceTexture|niTexture *Optional*. The texture to assign to the new decal.
--- @param priority? number *Default*: `0`. The desired sorting priority of the decal. Whenever a new decal is added, decals are resorted to give priority to decals with a higher number. Only 8 textures will ever be rendered at a time, leaving lower priority decals to potentially go unseen.
--- @param allowDuplicates? boolean *Default*: `false`. If true, duplicates of the same texture can be added. Normally, an existing decal of the same texture will be returned instead.
--- @return niTexturingPropertyMap|nil map A newly created decal map.
--- @return integer|nil index The index of the newly added decal map.
function niTexturingProperty:addDecalMap(texture, priority, allowDuplicates) end

--- Finds an existing decal applied to the property.
--- @param textureOrFileName niRenderedTexture|niSourceTexture|niTexture|string The texture or file name of the source texture to find.
--- @return niTexturingPropertyMap|nil map The existing map.
--- @return integer|nil index The index of the existing decal map.
function niTexturingProperty:getDecalMap(textureOrFileName) end

--- Attempts to remove all decal maps.
function niTexturingProperty:removeAllDecalMaps() end

--- Attempts to remove a decal at a given index.
--- @param index ni.texturingPropertyMapType The index of the decal to remove. The available indices are between `ni.texturingPropertyMapType.decalFirst` and `ni.texturingPropertyMapType.decalLast`.
--- @return boolean removed True if the decal was removed.
function niTexturingProperty:removeDecalMap(index) end

