-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- @meta
--- A pair of vectors marking a bounding box.
--- @class tes3boundingBox
--- @field max tes3vector3 The maximum bound of the box.
--- @field min tes3vector3 The minimum bound of the box.
tes3boundingBox = {}

--- Converts the bounding box to a string with 2 decimal places. The minimum bounds are printed first, then the maximal bounds.
--- @return string result No description yet available.
function tes3boundingBox:__tostring() end

--- Creates a copy of the bounding box.
--- @return tes3boundingBox result No description yet available.
function tes3boundingBox:copy() end

--- Checks if another bounding box intersects this one. This can be used to see if objects are "too close together".
--- @param other tes3boundingBox The other bounding box to check.
--- @return boolean result No description yet available.
function tes3boundingBox:intersects(other) end

--- Returns a table containing the 8 vertices comprising this bounding box.
--- @return tes3vector3[] result No description yet available.
function tes3boundingBox:vertices() end

