--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- An animation keyframe definition.
--- @class tes3keyframeDefinition
--- @field animationGroups tes3animationGroup *Read-only*. The first animation group associated with the keyframe definition.
--- @field filename string|nil *Read-only*. The filename associated with the keyframe definition.
--- @field groupCount number *Read-only*. The number of animation groups defined.
--- @field namedGroups table<string, tes3animationGroup> *Read-only*. A dictionary mapping a named animation group to the associated group data.
--- @field refCount number *Read-only*. 
--- @field sequences niSequence[] *Read-only*. The three sequences for the definition.
