--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- A lua event that is part of an animation group sound event.
--- @class tes3animationGroupLuaEvent
--- @field id string The ID of the lua event.
--- @field param string The param of the lua event.
