--- @meta

-- This file is autogenerated. Do not edit this file manually. Your changes will be ignored.
-- More information: https://github.com/MWSE/MWSE/tree/master/docs

--- A data structure that handles the weather.
--- @class tes3weatherController
--- @field ambientPostSunriseTime number Hours added after `sunriseDuration` before the ambient sunrise transition ends. The transition ends at `sunriseHour + sunriseDuration + ambientPostSunriseTime`; the sunrise color is the midpoint, not the color at this field's value. This is an offset, not an absolute hour.
--- @field ambientPostSunsetTime number Hours added after `sunsetDuration` before the ambient sunset transition ends. The transition ends at `sunsetHour + sunsetDuration + ambientPostSunsetTime`; the sunset color is the midpoint, not the color at this field's value. This is an offset, not an absolute hour.
--- @field ambientPreSunriseTime number Hours before `sunriseHour` when the ambient-color transition begins. The window is `sunriseHour - ambientPreSunriseTime` through `sunriseHour + sunriseDuration + ambientPostSunriseTime`, split between night → `ambientSunriseColor` and `ambientSunriseColor` → day. This is an offset, not an absolute hour.
--- @field ambientPreSunsetTime number Hours before `sunsetHour` when the ambient-color transition begins. The window is `sunsetHour - ambientPreSunsetTime` through `sunsetHour + sunsetDuration + ambientPostSunsetTime`, split between day → `ambientSunsetColor` and `ambientSunsetColor` → night. This is an offset, not an absolute hour.
--- @field currentFogColor tes3vector3 The current fog color. The values can range from 0 to 1.
--- @field currentSkyColor tes3vector3 The current sky color. The values can range from 0 to 1.
--- @field currentWeather tes3weather|tes3weatherAsh|tes3weatherBlight|tes3weatherBlizzard|tes3weatherClear|tes3weatherCloudy|tes3weatherCustom|tes3weatherFoggy|tes3weatherOvercast|tes3weatherRain|tes3weatherSnow|tes3weatherThunder *Read-only*. The current weather.
--- @field daysRemaining number The days remaining for the current weather.
--- @field fogDepthChangeSpeed number Duration, in in-game hours, used to interpolate land-fog depth from night to day after `sunriseHour` and from day to night after `sunsetHour`. It controls land-fog depth, not fog color.
--- @field fogPostSunriseTime number Hours added after `sunriseDuration` before the fog sunrise transition ends. The transition ends at `sunriseHour + sunriseDuration + fogPostSunriseTime`; the sunrise color is the midpoint, not the color at this field's value. This is an offset, not an absolute hour.
--- @field fogPostSunsetTime number Hours added after `sunsetDuration` before the fog sunset transition ends. The transition ends at `sunsetHour + sunsetDuration + fogPostSunsetTime`; the sunset color is the midpoint, not the color at this field's value. This is an offset, not an absolute hour.
--- @field fogPreSunriseTime number Hours before `sunriseHour` when the fog-color transition begins. The window is `sunriseHour - fogPreSunriseTime` through `sunriseHour + sunriseDuration + fogPostSunriseTime`, split between night → `fogSunriseColor` and `fogSunriseColor` → day. This is an offset, not an absolute hour.
--- @field fogPreSunsetTime number Hours before `sunsetHour` when the fog-color transition begins. The window is `sunsetHour - fogPreSunsetTime` through `sunsetHour + sunsetDuration + fogPostSunsetTime`, split between day → `fogSunsetColor` and `fogSunsetColor` → night. This is an offset, not an absolute hour.
--- @field hoursBetweenWeatherChanges number The hours between weather changes. Stored as a float value.
--- @field hoursRemaining number The hours remaining.
--- @field lastActiveRegion tes3region *Read-only*. Provides read-only access to last active region object.
--- @field masser tes3moon *Read-only*. Provides read-only access to the Masser moon object.
--- @field nextWeather tes3weather|tes3weatherAsh|tes3weatherBlight|tes3weatherBlizzard|tes3weatherClear|tes3weatherCloudy|tes3weatherCustom|tes3weatherFoggy|tes3weatherOvercast|tes3weatherRain|tes3weatherSnow|tes3weatherThunder *Read-only*. The next weather.
--- @field particlesActive tes3weatherControllerParticle[] *Read-only*. Provides a list of active weather particles.
--- @field particlesInactive tes3weatherControllerParticle[] *Read-only*. Provides a list of inactive weather particles.
--- @field precipitationFallSpeed number The z component of the rain or snow fall particle velocity (not including blizzards). Snow fall velocity is also multiplied by `snowFallSpeedScale`. This value is initialized by the "Precipitation Gravity" entry in morrowind.ini.
--- @field sceneAtmosphere niBSAnimationNode|niBSParticleNode|niBillboardNode|niCollisionSwitch|niNode|niSortAdjustNode|niSwitchNode *Read-only*. Provides access to the scene atmosphere skydome NiNode.
--- @field sceneClouds niBSAnimationNode|niBSParticleNode|niBillboardNode|niCollisionSwitch|niNode|niSortAdjustNode|niSwitchNode *Read-only*. Provides access to the scene clouds root NiNode.
--- @field sceneNightSky niBSAnimationNode|niBSParticleNode|niBillboardNode|niCollisionSwitch|niNode|niSortAdjustNode|niSwitchNode *Read-only*. Provides access to the scene night sky (stars and nebula) NiNode.
--- @field sceneRainRoot niBSAnimationNode|niBSParticleNode|niBillboardNode|niCollisionSwitch|niNode|niSortAdjustNode|niSwitchNode *Read-only*. Provides access to the scene rain root NiNode.
--- @field sceneSkyLight niDirectionalLight *Read-only*. Provides access to the scene sky light directional light.
--- @field sceneSkyRoot niBSAnimationNode|niBSParticleNode|niBillboardNode|niCollisionSwitch|niNode|niSortAdjustNode|niSwitchNode *Read-only*. Provides access to the scene sky root NiNode.
--- @field sceneSnowRoot niBSAnimationNode|niBSParticleNode|niBillboardNode|niCollisionSwitch|niNode|niSortAdjustNode|niSwitchNode *Read-only*. Provides access to the scene snow root NiNode.
--- @field sceneStormRoot niBSAnimationNode|niBSParticleNode|niBillboardNode|niCollisionSwitch|niNode|niSortAdjustNode|niSwitchNode *Read-only*. Provides access to the scene storm root NiNode.
--- @field sceneSunBase niBSAnimationNode|niBSParticleNode|niBillboardNode|niCollisionSwitch|niNode|niSortAdjustNode|niSwitchNode *Read-only*. Provides read-only access to the scenesun base NiNode.
--- @field sceneSunGlare niBSAnimationNode|niBSParticleNode|niBillboardNode|niCollisionSwitch|niNode|niSortAdjustNode|niSwitchNode *Read-only*. Provides read-only access to the scene sun glare NiNode.
--- @field sceneSunVis niBSAnimationNode|niBSParticleNode|niBillboardNode|niCollisionSwitch|niNode|niSortAdjustNode|niSwitchNode *Read-only*. Provides read-only access to the scene sun vis NiNode.
--- @field secunda tes3moon *Read-only*. Provides read-only access to the Secunda moon object.
--- @field skyPostSunriseTime number Hours added after `sunriseDuration` before the sky sunrise transition ends. The transition ends at `sunriseHour + sunriseDuration + skyPostSunriseTime`; the sunrise color is the midpoint, not the color at this field's value. This is an offset, not an absolute hour.
--- @field skyPostSunsetTime number Hours added after `sunsetDuration` before the sky sunset transition ends. The transition ends at `sunsetHour + sunsetDuration + skyPostSunsetTime`; the sunset color is the midpoint, not the color at this field's value. This is an offset, not an absolute hour.
--- @field skyPreSunriseTime number Hours before `sunriseHour` when the sky-color transition begins. The window is `sunriseHour - skyPreSunriseTime` through `sunriseHour + sunriseDuration + skyPostSunriseTime`, split between night → `skySunriseColor` and `skySunriseColor` → day. This is an offset, not an absolute hour.
--- @field skyPreSunsetTime number Hours before `sunsetHour` when the sky-color transition begins. The window is `sunsetHour - skyPreSunsetTime` through `sunsetHour + sunsetDuration + skyPostSunsetTime`, split between day → `skySunsetColor` and `skySunsetColor` → night. This is an offset, not an absolute hour.
--- @field snowFallSpeedScale number A multipler for the z component of snow fall particle velocity (not including blizzards). The z component is set by `precipitationFallSpeed * snowFallSpeedScale`. This value is initialized by the "Snow Gravity Scale" entry in morrowind.ini.
--- @field starsFadingDuration number Duration, in in-game hours, of each star fade. Opacity rises from 0 to 1 between `starsPostSunsetStart` and `starsPostSunsetStart + starsFadingDuration`, and falls from 1 to 0 between `starsPreSunriseFinish` and `starsPreSunriseFinish + starsFadingDuration`.
--- @field starsPostSunsetStart number Absolute game hour when the stars start fading in. At construction, this is initialized as `sunsetHour +` the `Morrowind.ini` offset (default `+1` hour); the field itself is then compared directly with the current game hour.
--- @field starsPreSunriseFinish number Absolute game hour when the stars start fading out. At construction, this is initialized as `sunriseHour -` the `Morrowind.ini` offset (default offset `2` hours); the field itself is then compared directly with the current game hour. Despite its name, it marks the start of the fade-out.
--- @field sunglareFaderAngleMax number The sunglare fader maximum angle.
--- @field sunglareFaderColor tes3vector3 The sunglare fader color. The values can range from 0 to 1.
--- @field sunglareFaderMax number The sunglare fader maximum.
--- @field sunPostSunriseTime number Hours added after `sunriseDuration` before the sunlight-color sunrise transition ends. The transition ends at `sunriseHour + sunriseDuration + sunPostSunriseTime`; the sunrise color is the midpoint, not the color at this field's value. This is an offset, not an absolute hour.
--- @field sunPostSunsetTime number Hours added after `sunsetDuration` before the sunlight-color sunset transition ends. The transition ends at `sunsetHour + sunsetDuration + sunPostSunsetTime`; the sunset color is the midpoint, not the color at this field's value. This is an offset, not an absolute hour.
--- @field sunPreSunriseTime number Hours before `sunriseHour` when the sunlight-color transition begins. The window is `sunriseHour - sunPreSunriseTime` through `sunriseHour + sunriseDuration + sunPostSunriseTime`, split between night → `sunSunriseColor` and `sunSunriseColor` → day. This is an offset, not an absolute hour.
--- @field sunPreSunsetTime number Hours before `sunsetHour` when the sunlight-color transition begins. The window is `sunsetHour - sunPreSunsetTime` through `sunsetHour + sunsetDuration + sunPostSunsetTime`, split between day → `sunSunsetColor` and `sunSunsetColor` → night. This is an offset, not an absolute hour.
--- @field sunriseDuration number Duration, in in-game hours, of the sun's sunrise motion/fade. It also contributes to every sunrise color window: that window lasts `Pre + sunriseDuration + Post` hours.
--- @field sunriseHour number Absolute in-game hour used as the sunrise reference. The sun's sunrise motion begins here; each ambient, fog, sky, and sunlight color transition may begin earlier or end later according to its `Pre` and `Post` settings.
--- @field sunsetDuration number Duration, in in-game hours, of the sun's sunset motion/fade. It also contributes to every sunset color window: that window lasts `Pre + sunsetDuration + Post` hours.
--- @field sunsetHour number Absolute in-game hour used as the sunset reference. Each ambient, fog, sky, and sunlight color transition may begin earlier or end later according to its `Pre` and `Post` settings.
--- @field thunderFlashIntensity number The active thunder flash intensity.
--- @field timescaleClouds string The timescale for clouds.
--- @field transitionScalar number The scalar transition.
--- @field underwaterColor tes3vector3 Color blended into weather colors while underwater. `underwaterColorWeight` controls the blend amount. Values range from 0 to 1.
--- @field underwaterColorWeight number Blend weight for `underwaterColor`: `0` keeps the normal weather color, and `1` replaces it with `underwaterColor`. Values are clamped to 0–1 during initialization.
--- @field underwaterDayFog number Underwater fog-density multiplier used during the daytime portion between the sunrise and sunset transitions.
--- @field underwaterIndoorFog number Underwater fog-density multiplier used in ordinary interior cells. Exterior-interior cells use the time-of-day underwater values instead.
--- @field underwaterNightFog number Underwater fog-density multiplier used during the nighttime portion outside the sunrise and sunset transitions.
--- @field underwaterSunriseFog number Underwater fog-density multiplier used at the sunrise endpoint. In exterior water, it is blended from `underwaterNightFog` toward `underwaterDayFog` using `sunriseHour` and the day midpoint.
--- @field underwaterSunsetFog number Underwater fog-density multiplier used at the sunset endpoint. In exterior water, it is blended from `underwaterDayFog` toward `underwaterNightFog` between `sunsetHour` and midnight.
--- @field weathers table<tes3.weather, tes3weather|tes3weatherAsh|tes3weatherBlight|tes3weatherBlizzard|tes3weatherClear|tes3weatherCloudy|tes3weatherCustom|tes3weatherFoggy|tes3weatherOvercast|tes3weatherRain|tes3weatherSnow|tes3weatherThunder> *Read-only*. Array-style table with weather objects for each weather type. The indices in the table map to the values in the [`tes3.weather`](https://mwse.github.io/MWSE/references/weather-types/) table.
--- @field windVelocityCurrWeather tes3vector3 The wind velocity for the current weather.
--- @field windVelocityNextWeather tes3vector3 The wind velocity for the next weather.
tes3weatherController = {}

--- Calculates the sun damage based on the current weather.
--- @return number result No description yet available.
function tes3weatherController:calcSunDamageScalar() end

--- Immediately switches the weather to the provided weather parameter.
--- @param weatherId tes3.weather Maps to values in the [`tes3.weather`](https://mwse.github.io/MWSE/references/weather-types/) table.
function tes3weatherController:switchImmediate(weatherId) end

--- Transitions the weather to the provided weather parameter based on the weather controller settings.
--- @param weatherId tes3.weather Maps to values in the [`tes3.weather`](https://mwse.github.io/MWSE/references/weather-types/) table.
function tes3weatherController:switchTransition(weatherId) end

--- Updates the weather controller visuals. This should be called after any weather transitions.
function tes3weatherController:updateVisuals() end

